# Site settings
title: nandosousa.com
email: nandosousafr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brazilian, Software developer and Science Groker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nandosousafr.github.com" # the base hostname & protocol for your site
twitter_username: nandosousafr
github_username:  nandosousafr
permalink: :title.html
keep_files:
  - categories
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
